const TRANSITIONS = Object.freeze({
  NEW: ["IDENTIFIED","ESCALATED","FAILED","CANCELED"],
  IDENTIFIED: ["QUALIFYING","ESCALATED","FAILED","CANCELED"],
  QUALIFYING: ["QUALIFIED","WAITING_CUSTOMER","ESCALATED","FAILED","CANCELED"],
  QUALIFIED: ["SCHEDULING","ESCALATED","FAILED","CANCELED"],
  SCHEDULING: ["SCHEDULED","WAITING_CUSTOMER","WAITING_EMPLOYEE","ESCALATED","FAILED","CANCELED"],
  SCHEDULED: ["JOB_IN_PROGRESS","CANCELED","ESCALATED","FAILED"],
  JOB_IN_PROGRESS: ["JOB_COMPLETED","WAITING_EMPLOYEE","ESCALATED","FAILED"],
  JOB_COMPLETED: ["INVOICED","WAITING_EMPLOYEE","ESCALATED","FAILED"],
  INVOICED: ["PAID","WAITING_PAYMENT","DISPUTED","FAILED"],
  WAITING_PAYMENT: ["PAID","DISPUTED","FAILED","CANCELED"],
  PAID: ["REVIEW_REQUESTED","RETAINED","CLOSED"],
  REVIEW_REQUESTED: ["RETAINED","CLOSED"],
  RETAINED: ["CLOSED","SCHEDULING"],
  WAITING_CUSTOMER: ["QUALIFYING","SCHEDULING","CANCELED","ESCALATED"],
  WAITING_EMPLOYEE: ["SCHEDULING","JOB_IN_PROGRESS","JOB_COMPLETED","INVOICED","ESCALATED","FAILED"],
  ESCALATED: ["QUALIFYING","SCHEDULING","JOB_IN_PROGRESS","INVOICED","CANCELED","FAILED"],
  DISPUTED: ["WAITING_PAYMENT","PAID","CLOSED"],
  FAILED: ["ESCALATED","DEAD_LETTER"],
  DEAD_LETTER: ["ESCALATED","CLOSED"],
  CANCELED: ["CLOSED"],
  CLOSED: []
});

export class StateMachine {
  canTransition(from, to) {
    return Boolean(TRANSITIONS[from]?.includes(to));
  }
  transition(workflow, to) {
    if (!this.canTransition(workflow.state, to)) throw new Error(`INVALID_TRANSITION:${workflow.state}->${to}`);
    return { ...workflow, state: to, version: workflow.version + 1 };
  }
}

export { TRANSITIONS };
